# Generated by Django 3.0.3 on 2020-03-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_user_subscribed_newsletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsLetterUsers',
            new_name='NewsLetterUser',
        ),
    ]
