
name: Continous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      run: |
        pipenv install --dev
    - uses: wemake-services/wemake-python-styleguide@0.13.4
    - name: Django Testing project
      run: |
        pipenv run manage.py test
